stages:
- deploy
- update

deploy:portal:
  stage: deploy
  only:
  - master
  tags:
  - docker
  image: docker-registry.mastersign.de/tk-docker/lftp
  script:
  - cd portal
  - lftp $FTP_TARGET_URL -c "user $FTP_USER,\"$FTP_PASSWORD\"; lpwd; pwd"

update:app-library-db:
  stage: update
  only:
  - schedules
  tags:
  - windows
  - powershell
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
    - db-update/downloads
  script:
  - .\\db-update\\Update-AppLibraryDatabase.ps1 -TargetUrl $env:FTP_TARGET_URL/bench-apps-db.json -User $env:FTP_USER -Password $env:FTP_PASSWORD
