stages:
- deploy

deploy:portal:
  stage: deploy
  only:
  - master
  except:
  - schedules
  - triggers
  tags:
  - docker
  image: docker-registry.mastersign.de/tk-docker/lftp
  script:
  - cd portal
  - lftp -u $FTP_USER,$FTP_PASSWORD -e "mirror -R -e -X bench-apps-db.json; exit" $FTP_TARGET_URL

update:app-library-db:
  stage: deploy
  only:
  - schedules
  - triggers
  tags:
  - windows
  - powershell
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
    - db-update/downloads
  script:
  - .\\db-update\\Update-AppLibraryDatabase.ps1 -TargetUrl $env:FTP_TARGET_URL/bench-apps-db.json -User $env:FTP_USER -Password $env:FTP_PASSWORD
