stages:
- update

update:app-library-db:
  stage: update
  only:
  - schedules
  tags:
  - windows
  - powershell
  cache:
    key: "$CI_COMMIT_SHA"
    untracked: true
    paths:
    - db-update/downloads
  script:
  - .\\db-update\\Update-AppLibraryDatabase.ps1
