stages:
- update

update:app-library-db:
  stage: update
  only:
  - schedules
  tags:
  - windows
  - powershell
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
    - db-update/downloads
  script:
  - .\\db-update\\Update-AppLibraryDatabase.ps1 -TargetUrl $env:FTP_TARGET_URL -User $env:FTP_USER -Password $env:FTP_PASSWORD
