stages:
- deploy
- update-db

deploy:portal:
  stage: deploy
  only:
  - master
  tags:
  - docker
  image: docker-registry.mastersign.de/tk-docker/lftp
  script:
  - lftp --help

update:app-library-db:
  stage: update-db
  only:
  - schedules
  - master
  tags:
  - windows
  - powershell
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
    - db-update/downloads
  script:
  - .\\db-update\\Update-AppLibraryDatabase.ps1 -TargetUrl $env:FTP_TARGET_URL -User $env:FTP_USER -Password $env:FTP_PASSWORD
